In [1]:
import tiktoken
import re

In [2]:
with open("the-verdict.txt", "r") as f:
    lines = f.read()

print(len(lines))

20479


In [3]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', lines)
preprocessed[:10]
preprocessed = [item for item in preprocessed if item.strip()]
print(len(preprocessed))

4690


In [4]:
all_words = sorted(set(preprocessed))
print(all_words[-10:])
vocab_size = len(all_words)
print(vocab_size)
vocab = {token: idx for idx, token in enumerate(all_words)}
i = 10
for i, word in enumerate(vocab):
    if i > 10:
        break
    print(word, vocab[word])

['would', 'wouldn', 'year', 'years', 'yellow', 'yet', 'you', 'younger', 'your', 'yourself']
1130
! 0
" 1
' 2
( 3
) 4
, 5
-- 6
. 7
: 8
; 9
? 10


In [5]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.token_to_int = vocab
        self.int_to_token = {idx: token for token, idx in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item for item in preprocessed if item.strip()]
        return [self.token_to_int[token] for token in preprocessed]
    
    def decode(self, integers):
        text = " ".join([self.int_to_token[idx] for idx in integers])
        # replaces spaces before punctuation marks for format sentences correctly
        text = re.sub(r'\s+([,.:;?_!"()\'])', r'\1', text)
        return text
    
tokenizer = SimpleTokenizerV1(vocab)
test = "their  was.."
print(tokenizer.encode(test))
print(tokenizer.decode(tokenizer.encode(test)))



[989, 1077, 7, 7]
their was..


In [6]:
all_words.extend(["<|unk|>", "<|endoftext|>"])
all_words
vocab = {token: idx for idx, token in enumerate(all_words)}
max = 10
for i, item in enumerate(list(vocab.items())[-5:]):
    if i > max:
        break
    print(item)
text1 = "Hi, do you like tea?"
text2 = "In the sunlit terraces"
text = " <|endoftext|> ".join((text1, text2))

print(text)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|unk|>', 1130)
('<|endoftext|>', 1131)
Hi, do you like tea? <|endoftext|> In the sunlit terraces


In [7]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.token_to_int = vocab
        self.int_to_token = {idx: token for  token, idx in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [item if item in self.token_to_int else "<|unk|>" for item in preprocessed]
        return [self.token_to_int[token] for token in preprocessed]

    def decode(self, integers):
        text = " ".join([self.int_to_token[idx] for idx in integers])
        # replaces spaces before punctuation marks for format sentences correctly
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

tokenizer = SimpleTokenizerV2(vocab)
encoded = tokenizer.encode(text)
# tokenizer.int_to_token.keys()
print(encoded)
decoded = tokenizer.decode(encoded)
print(decoded)
print(tokenizer.decode(tokenizer.encode(text)))


[1130, 5, 355, 1126, 628, 975, 10, 1131, 55, 988, 956, 984]
<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces
<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces


In [8]:
bpe_tokenizer = tiktoken.get_encoding("gpt2")
text = (
"Hello, do you like tea? <|endoftext|> In the sunlit terraces"
"of someunknownPlace."
)
encoded = bpe_tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(encoded)
strings = bpe_tokenizer.decode(encoded)
print(strings)


[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]
Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [9]:
new_word = "Akwirw ier"

encoded = bpe_tokenizer.encode(new_word)
print(encoded)
decoded = bpe_tokenizer.decode(encoded)
print(decoded)

[33901, 86, 343, 86, 220, 959]
Akwirw ier


In [10]:
with open("the-verdict.txt", "r") as f:
    lines = f.read()

print(len(lines))
all_words = sorted(set(preprocessed))
all_words.extend(["<|unk|>", "<|endoftext|>"])
print(all_words[-10:])
vocab_size = len(all_words)
enc_text = bpe_tokenizer.encode(lines)
vocab_size = len(enc_text)
print(enc_text[:10])



20479
['year', 'years', 'yellow', 'yet', 'you', 'younger', 'your', 'yourself', '<|unk|>', '<|endoftext|>']
[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138]


In [11]:
block_size = 2
enc_sample = enc_text[50:]
for i in range(block_size):
    x = enc_sample[i:block_size]
    y = enc_sample[i+1:i+block_size+1]
    print(x)
    print(y)
    print(bpe_tokenizer.decode(x), "-->", bpe_tokenizer.decode(y))
    break


[290, 4920]
[4920, 2241]
 and established -->  established himself


In [46]:
import torch
from torch.utils.data import DataLoader, Dataset

class GPTDatasetV1(Dataset):
    def __init__(self, text, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []
        self.encoded = tokenizer.encode(text)
        #max_length = block_size or context_length, so need to substract max_length from range as that will be size of the sliced array 
        for i in range(0, len(self.encoded) - max_length, stride):
            input_chunk = self.encoded[i:i+max_length]
            targets = self.encoded[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(targets))
    
    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, idx):
        return (self.input_ids[idx], self.target_ids[idx])


dataset = GPTDatasetV1(lines, tokenizer, 4, 1)
dataset[1]




(tensor([  44,  149, 1003,   57]), tensor([ 149, 1003,   57,   38]))

In [52]:

def create_dataloader_v1(text, batch_size, max_length, stride, shuffle=True, drop_last=True, num_workers=0):
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(text, tokenizer=tokenizer, max_length=max_length, stride=stride)
    dataloader = DataLoader(dataset, batch_size=batch_size, num_workers=num_workers, drop_last=drop_last, shuffle=shuffle)
    return dataloader

dataloader = create_dataloader_v1(lines, batch_size=4, max_length=4, stride=1, shuffle=False)

first_batch = next(iter(dataloader))

first_batch

[tensor([[  40,  367, 2885, 1464],
         [ 367, 2885, 1464, 1807],
         [2885, 1464, 1807, 3619],
         [1464, 1807, 3619,  402]]),
 tensor([[ 367, 2885, 1464, 1807],
         [2885, 1464, 1807, 3619],
         [1464, 1807, 3619,  402],
         [1807, 3619,  402,  271]])]

In [54]:

dataloader = create_dataloader_v1(lines, batch_size=4, max_length=4, stride=3, shuffle=False)

first_batch = next(iter(dataloader))

first_batch

[tensor([[   40,   367,  2885,  1464],
         [ 1464,  1807,  3619,   402],
         [  402,   271, 10899,  2138],
         [ 2138,   257,  7026, 15632]]),
 tensor([[  367,  2885,  1464,  1807],
         [ 1807,  3619,   402,   271],
         [  271, 10899,  2138,   257],
         [  257,  7026, 15632,   438]])]